//> using scala "3.2.0"
//> using jar "lib/stainless-library.jar"
//> using jar "lib/stainless-library-sources.jar"
//> using dep "org.scalameta::munit::0.7.29"
//> using options "-Wconf:msg=not.*?exhaustive:s,msg=pattern.*?specialized:s"
